"""add task priority, user role, bookmarks

Revision ID: 2c59ab90cc7e
Revises: 600e07e0ae58
Create Date: 2026-09-23 12:23:03.216632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c59ab90cc7e'
down_revision: Union[str, Sequence[str], None] = '600e07e0ae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

task_priority_enum = sa.Enum('low', 'medium', 'high', name='taskpriority')
user_role_enum = sa.Enum('member', 'admin', name='userrole')


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate doesn't emit CREATE TYPE for a bare ALTER TABLE ADD COLUMN on Postgres
    # (it only does that as a side effect of CREATE TABLE), so the enum types need to be
    # created explicitly before the columns that use them.
    bind = op.get_bind()
    task_priority_enum.create(bind, checkfirst=True)
    user_role_enum.create(bind, checkfirst=True)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_bookmark_user_task')
    )
    # server_default so this also works against a table that already has rows (matches
    # the ORM-side defaults in app/models/task.py and app/models/user.py).
    op.add_column('tasks', sa.Column('priority', task_priority_enum, nullable=False, server_default='medium'))
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='member'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('tasks', 'priority')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###

    bind = op.get_bind()
    user_role_enum.drop(bind, checkfirst=True)
    task_priority_enum.drop(bind, checkfirst=True)
