from sqlalchemy.orm import Session

from app.models.comment import Comment


def get_comment(db: Session, comment_id: int) -> Comment | None:
    return db.get(Comment, comment_id)


def create_comment(db: Session, *, content: str, task_id: int, author_id: int) -> Comment:
    # No commit here, unlike the other repositories: this needs to be composable into a
    # larger atomic transaction (see services/task.py::assign_task, which bundles a
    # comment insert with a task update into a single commit). flush() is enough to get
    # the autogenerated id/created_at without ending the transaction. Standalone callers
    # (services/comment.py) commit for themselves right after calling this.
    db_comment = Comment(content=content, task_id=task_id, author_id=author_id)
    db.add(db_comment)
    db.flush()
    db.refresh(db_comment)
    return db_comment


def delete_comment(db: Session, db_comment: Comment) -> None:
    db.delete(db_comment)
