USER_EMAIL_MAX_LENGTH = 255
USERNAME_MAX_LENGTH = 50
USER_HASHED_PASSWORD_MAX_LENGTH = 255

PROJECT_NAME_MAX_LENGTH = 150

TASK_TITLE_MAX_LENGTH = 200

TAG_NAME_MAX_LENGTH = 50

COMMENT_CONTENT_MIN_LENGTH = 1
COMMENT_CONTENT_MAX_LENGTH = 2000

TAGS_CACHE_KEY = "tags:all"
TAGS_CACHE_TTL_SECONDS = 300
